erp_report/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'erp/',include('report.urls')),
]

report/urls.py
from django.conf.urls import url
# import report.views
from report.views import charts, views
app_name ='report'
urlpatterns = [
    # url(r'^synchronous-report-current/', views.synchronous_report_current, name='current'),
    # url(r'^save-report/', views.save_report, name='save'),
    # url(r'^(?P<pk>[0-9]+)/synchronous-report/$', views.synchronous_report, name='synchronous_report'),
    url(r'^mrp-calculator/', views.mrp_calculator, name='mrp-calculator'),
    url(r'^dashboard/(?P<year>[0-9]+)/$', charts.dashboard, name='dashboard'),
    # url(r'^area/(?P<product>([\w& ]+))/$', charts.area, name='area'),
    url(r'^detail/(?P<product>([\w& -]+))/$', charts.detail, name='detail'),
    # url(r'^report-preview/', views.report_preview, name='report-preview'),
]
#
#synchronous-report

report/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import datetime

from django.db import models

# Create your models here.

class Report(models.Model):
    name = models.CharField(max_length=50)
    created = models.DateTimeField(default=datetime.now, blank=True)
    input = models.CharField(max_length=50)
    result = models.TextField()

report/views/charts.py
from django.http import HttpResponse,Http404
from django.shortcuts import render, redirect
from report.rest import *
# import report.tests
from django.views.decorators.clickjacking import xframe_options_exempt
from report.utils import *
from report.tests import *

g_production=[]
g_plan ={}
g_year =2017


@xframe_options_exempt
def dashboard(request,year):
    try:
        # token = request.META['HTTP_TOKEN']
        token = "hsadj12312328"
        is_valid = True
        if is_valid:
            request.session['token'] = token
        else:
            raise Http404("You do not have permission")
    except:
        raise Http404("You do not have permission")

    global g_production
    global g_plan
    global g_year
    g_year = year
    g_plan = get_reality_production_detail(year)
    g_production = get_reality_production(year)

    # g_production = production_test
    # g_plan = production_plan_test
    if bool(g_production):
        return render(request,'dashboard.html',{'production':g_production,'production_plan':g_plan,'year':year})
    return HttpResponse("Data is empty")

@xframe_options_exempt
def detail(request,product):
    token = request.session.get('token', False)
    if not token:
        raise Http404("You do not have permission")
    global g_production
    global g_plan
    global g_year
    data = g_plan
    # print data2
    # data = production_plan_test
    # # print data
    production_plan = data[product]
    # print production_plan
    if bool(production_plan):
        line = {}
        type = ["mua_sam","san_xuat","kinh_doanh"]
        # type_plan = ["hang_ve_kh", "san_xuat_kh", "kinh_doanh_kh"]
        xArray = [0,1,2,3,4,5,6,7,8,9,10,11]
        for key in type:
            yArray = production_plan[key]['thuc_te_thang']
            line_near_reality = linear_regression(xArray,yArray)
            yArray = production_plan[key]['ke_hoach_thang']
            line_near_plan = linear_regression(xArray, yArray)
            line[key] = {
                'ke_hoach_thang':line_near_plan,
                'thuc_te_thang':line_near_reality
            }
        print base_url
        return render(request,'production_plan_detail.html',{'production':g_production,'production_plan':production_plan,'line':line,'product':product,'year':g_year,'api_url':base_url})
    return HttpResponse("Data is empty")

report/views/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from report import mrp2, data_30
from report.rest import *
import json
from report.mrp import *
from django.utils import timezone
from report.models import *
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt
from report.tests import *

@csrf_exempt
def mrp_calculator(request):
    if request.method == 'POST':
        # print request.body
        json_data = json.loads(request.body.decode(encoding='UTF-8'))
        data = json_data['data']
        # data = data2.data
        mrp2.bom = data['bom']
        mrp2.materials = data['materials']
        result = mrp2.main()
        result_json = json.dumps(result)
        # print result_json
        return HttpResponse(result_json)
    return HttpResponse('Hello, this is mrp calculator api. Method POST, body: {"data":your_dict}')


def check_minimum(bom, materials,required):
    check_result ={}
    for key, value in bom.iteritems():
        # print key
        sum =0
        min = value[1]*required
        for v in value[0]:
           sum = sum + int(materials[v])
        if sum < min:
            check_result[key] = [value[0],min-sum]
    # print check_result
    return check_result
    # result_json = json.dumps(check_result)

report/templates/area.html
{% extends "app_base.html" %}
{% load template_tag_extras %}
{% block page_content %}

		<div class="row">
			<div class="col-sm-1"></div>
			<div class="col-sm-10">
				<div id ='areaChart' align="center"></div>
			</div>

		</div>

{% endblock%}
{% block page_scripts %}
<script>
	var chartname = "Kế hoạch sản xuất kinh doanh " + "{{product}}"
	var colors = ["#F44336","#673AB7","#03A9F4","#4CAF50","#FFEB3B","#FF5722","#607D8B","#9C27B0","#795548"]

	var type = {
	"ke_hoach":"Kế hoạch",
	"hang_ve":"Hàng về",
	"san_xuat":"Sản xuất",
	"kinh_doanh":"Kinh doanh"};

	var assign_series=[]
	var assign_data = {{assign | js}}

	var count =0;
    for (var key in  type){
    	name = 	type[key]
    	values = assign_data[key]['months']
    	assign_series.push(
    		{'values':values,
    		'text':name,
    		'backgroundColor1':colors[count],
    		'backgroundColor2':colors[count],
    		"line-color":colors[count],
    		})
    	count ++
    }
	console.log(assign_series)
    var areaConfig = {
  backgroundColor : "#fff",
  globals : {
    shadow : false,
    fontFamily : "Helvetica"
  },
 	type: "area",
 	title :{
 	  text : chartname,
 	  fontColor : "#5f5f5f",
 	  backgroundColor : "transparent",
 	  textAlign : "left",
 	  padding: "15px 15px",
 	  fontSize : "20px"
 	},
 	legend : {
    "layout": "x4",
    toggleAction:'remove',
    backgroundColor:'#FBFCFE',
    borderWidth:0,
    adjustLayout:true,
    align:'center',
    verticalAlign:'bottom',
    marker: {
        type:'circle',
        cursor:'pointer',
        borderWidth:0,
        size:6
    },
    item: {
        fontColor: "#777",
        cursor:'pointer',
        offsetX:-6,
        fontSize:12
    },
    mediaRules:[
        {
            maxWidth:500,
            visible:false
        }
    ]
 	},
 	scaleX : {
 	  maxItems : 12,
 	  transform : {
 	    type : 'date'
 	  },
 	  zooming : true,
 	  values : ['Tháng 1','Tháng 2','Tháng 3','Tháng 4','Tháng 5','Tháng 6','Tháng 7',
 	  			'Tháng 8','Tháng 9','Tháng 10','Tháng 11','Tháng 12'],
 	  lineColor : "#5f5f5f",
 	  lineWidth : "1px",
 	  tick : {
 	    lineColor : "#5f5f5f",
 	    lineWidth : "1px"
 	  },
 	  item : {
 	    fontColor : "#5f5f5f"
 	  },
 	  guide : {
 	    visible : false
 	  }
 	},
 	scaleY : {
 	  lineColor : "#5f5f5f",
 	  lineWidth : "1px",
 	  tick : {
 	    lineColor : "#5f5f5f",
 	    lineWidth : "1px"
 	  },
 	  guide : {
 	    lineStyle : "solid",
 	    lineColor : "#626262"
 	  },
 	   item : {
 	    fontColor : "#5f5f5f"
 	  },
 	},
 	tooltip : {
 	  visible : false
 	},
 	crosshairX :{
 	  scaleLabel : {
 	    backgroundColor : "#fff",
 	    fontColor : "black",
 	    borderColor:"#333",
 	    borderWidth: 1,
 	    borderRadius: 3
 	  },
 	  plotLabel :{
 	    backgroundColor : "#434343",
 	    fontColor : "#FFF"
 	  }
 	},
 	plot : {
 	  "contour-on-top":false,
 	  alphaArea : 1,
 	  lineWidth : "2px",
 	  aspect : "spline",
 	  marker : {
 	    visible : false
 	  },
 	  animation:{
      delay: 500,
      effect: "ANIMATION_SLIDE_TOP",
      speed: 700,
      method: 0,
      sequence: 1
 	  }
 	},
	series : assign_series
};

zingchart.render({
	id : 'areaChart',
	data : areaConfig,
	height: '100%',
	width: '100%' ,
});
</script>
{% endblock%}

report/templates/base/app_base.html
{% load staticfiles %}
{% load template_tag_extras %}
<title>VNPT-Technology ERP</title>
<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
<script src="{% static 'zingchart/zingchart.min.js' %}"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<script src="{% static 'report_preview.js' %}"></script>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet"
      type="text/css"/>
<link href="{% static 'global/plugins/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet"/>
<link href="{% static 'global/plugins/simple-line-icons/simple-line-icons.min.css' %}" rel="stylesheet"/>
<link href="{% static 'global/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
<link href="{% static 'global/plugins/bootstrap-toastr/toastr.min.css' %}" rel="stylesheet">
<link href="{% static 'global/plugins/uniform/css/uniform.default.css' %}" rel="stylesheet"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN THEME STYLES -->
<link href="{% static 'global/css/components.css' %}" id="style_components" rel="stylesheet"/>
<link href="{% static 'global/css/plugins.css' %}" rel="stylesheet"/>
<link href="{% static 'admin/layout/css/layout.css' %}" rel="stylesheet"/>
<link href="{% static 'admin/pages/css/login.css' %}" rel="stylesheet"/>
<!--<link href="{% static 'admin/layout/css/themes/darkblue.css' %}" rel="stylesheet" id="style_color"/>-->
<link href="{% static 'admin/layout/css/themes/blue.css' %}" rel="stylesheet" id="style_color"/>
<link href="{% static 'admin/layout/css/custom.css' %}" rel="stylesheet"/>
<link href="{% static 'snippet/snippet.css' %}" rel="stylesheet"/>
<!--<link href="{% static 'global/css/bootstrap-duallistbox.min.css' %}" rel="stylesheet" />-->
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>

<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<!-- BEGIN CORE PLUGINS -->
<!--[if lt IE 9]>
<script src="{% static 'global/plugins/respond.min.js' %}"></script>
<script src="{% static 'global/plugins/excanvas.min.js' %}"></script>
<![endif]-->
<script src="{% static 'global/plugins/jquery.min.js' %}"></script>
<script src="{% static 'global/plugins/jquery-migrate.min.js' %}"></script>
<script src="{% static 'global/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'global/plugins/jquery.blockui.min.js' %}"></script>
<script src="{% static 'global/plugins/uniform/jquery.uniform.min.js' %}"></script>
<script src="{% static 'global/plugins/jquery-validation/js/jquery.validate.min.js' %}" type="text/javascript"></script>
<script src="{% static 'global/plugins/bootstrap-toastr/toastr.min.js' %}"></script>
<script src="{% static 'admin/pages/scripts/ui-toastr.js' %}"></script>
<script src="{% static 'global/scripts/metronic.js' %}"></script>
<!--<script src="{% static 'global/scripts/js.cookie.js' %}"></script>-->
<script src="{% static 'admin/layout/scripts/layout.js' %}"></script>
<!--<script src="{% static 'global/scripts/jquery.bootstrap-duallistbox.min.js' %}"></script>-->


<!--&lt;!&ndash; ssdc epl js &ndash;&gt;-->
<!--<script src="{% static 'common.js' %}"></script>-->
<!--<script src="{% static 'ajax-client.js' %}"></script>-->

<script>
jQuery(document).ready(function() {
    Metronic.init(); // init metronic core components
    Layout.init(); // init current layout
});



</script>
<div class="page-header navbar navbar-fixed-top" >

    <div class="page-header-inner">
            <div class="page-logo">
                <img src="{% static 'img/logo_vnpt_big.png' %}" alt="logo" class="logo-default">

		    </div>
            <ul class="nav navbar-nav" id="item_menu">
                <li data-toggle="modal" data-target="#loading" onclick="loading()">
                    <a href="{% url 'report:dashboard' year %}"><b style="color:white;">Dashboard </b></a></li>
                {% for p in production %}
                <li><a href="{% url 'report:detail' p.name %}"><b style="color:white;">{{p.name}}</b></a></li>
                {% endfor %}
            </ul>

    </div>
</div>
<div>
    <!--<div class="col-md-1 sidebar-content " style="padding-top:50px">-->
        <!--<ul class="ver-inline-menu tabbable margin-bottom-25">-->
            <!--<li  data-toggle="modal" data-target="#loading" onclick="loading()"><a-->
                        <!--href="{% url 'report:dashboard' year %}"><b>Dashboard</b> </a></li>-->
            <!--{% for p in production %}-->
            <!--<li><a href="{% url 'report:detail' p.name %}" ><b>{{p.name}}</b></a></li>-->
                <!--{% endfor %}-->
        <!--</ul>-->
    <!--</div>-->
    <div class="col-md-12">
        {% block page_content %}
        {% endblock%}
    </div>

    <div class="modal fade" id="loading" role="dialog">
        <div class="modal-dialog" align="center" style="padding-top:50%">
                <div class="osahanloading"></div>
        </div>
    </div>
</div>
{% block page_scripts %}

{% endblock %}

report/templates/business.html
{% extends "app_base.html" %}
{% load template_tag_extras %}
{% block page_content %}

		<div class="row">
			<div class="col-sm-1"></div>
			<div class="col-sm-10">
				<div id ='businessChart' align="center"></div>
			</div>

		</div>

{% endblock%}
{% block page_scripts %}
<script>
var chartname = "Kế hoạch kinh doanh " + "{{product}}"
	var colors = ["#F44336","#673AB7","#03A9F4","#4CAF50","#FFEB3B","#FF5722","#607D8B","#9C27B0","#795548"]

	var type = {
	"ke_hoach":"Kế hoạch",
	"hang_ve":"Hàng về",
	"san_xuat":"Sản xuất",
	"kinh_doanh":"Kinh doanh"};

	var business_series=[]
	var business_data = {{business | js}}
    var line = {{line | js}}
	var count =0;
    for (var key in  type){
    	name = 	type[key]
    	values = business_data[key]['months']
    	business_series.push(
    		{'values':values,
    		'text':name,
    		'type':'bar',
    		'backgroundColor':colors[count]
    		})
    	business_series.push(
    	{
    	    "type":"line",
            "values":line[key],
            "text":"Linear (" + type[key] +")",
    	}
    	)
    count ++
    }
	console.log(business_series)
	var businessConfig = {
  "type":"mixed",
  "title":{
    "text":chartname
  },
  legend : {
    "layout": "2x4",
    toggleAction:'remove',
    backgroundColor:'#FBFCFE',
    borderWidth:0,
    adjustLayout:true,
    align:'center',
    verticalAlign:'bottom',
    marker: {
        type:'circle',
        cursor:'pointer',
        borderWidth:0,
        size:6
    },
    item: {
        fontColor: "#777",
        cursor:'pointer',
        offsetX:-6,
        fontSize:12
    },
    mediaRules:[
        {
            maxWidth:500,
            visible:false
        }
    ]
 	},
  "plot":{
  	"marker":{
      "size":1

    },
    "tooltip":{
      "text":"%t: %v",
      "thousands-separator":","
    }
  },
  "scale-x":{
    "labels":['Tháng 1','Tháng 2','Tháng 3','Tháng 4','Tháng 5','Tháng 6','Tháng 7',
 	  			'Tháng 8','Tháng 9','Tháng 10','Tháng 11','Tháng 12']
  },
  "scale-y":{
    "min-value":"0",
},
  "series":business_series
};

zingchart.render({
	id : 'businessChart',
	data : businessConfig,
	height: "100%",
	width: "100%"
});
</script>
{% endblock%}

report/templates/create_report.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}

<style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 80px;
  height: 80px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
<head>
  <title>ERP Report</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script src="{% static 'current.js' %}"></script>
</head>
<body>



<div class="container">

  <form id="create-report" method="POST" action="#">
    {% csrf_token %}
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-2">
            <p style="padding-top:0.5em">Báo cáo theo: </p>
        </div>
        <div class="col-md-6">
            <select id="products" class="btn btn-nomarl" name="product" onClick="selectProduct()">
                <option value="month">Tháng</option>
                <option value="quarter">Quý</option>
                <option value="year">Năm</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-2">
            <p style="padding-top:0.5em">Thời gian báo cáo: </p>
        </div>
        <div class="col-md-2">

        </div>
        <div class="col-md-2">

        </div>
    </div>
    <div class="row">
        <div class="col-md-5"></div>
        <div class="col-md-2">
            <button class="btn btn-primary" onclick="create()" id="createReport">Tạo báo cáo</button>
        </div>

    </div>

</form>
    <div class="row" style="padding-top:0.5em; padding-left:2em">
        <div class="col-md-5"></div>
        <div class="col-md-2">
            <div class="loader" style="display: none;" id="loading"></div>
        </div>
    </div>


</div>

</body>
</html>

report/templates/dashboard.html
{% extends "app_base.html" %}
<!--{% load template_tag_extras %}-->


{% block page_content %}
<div style="padding-top:50px">
    <div class="row" >
        <div class="col-sm-5">
            <div class="portlet light bordered" >
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-bar-chart font-green-haze"></i>
                        <span class="caption-subject bold uppercase font-green-haze"> Kế hoạch sản xuất</span>
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
                        <a href="javascript:;" class="fullscreen" data-original-title="" title=""></a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div id='circleChart' ></div>
                </div>
            </div>
        </div>
        <div class="col-sm-7">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-bar-chart font-green-haze"></i>
                        <span class="caption-subject bold uppercase font-green-haze">Kế hoạch sản xuất và thực tế</span>
                    </div>
                    <div class="tools">
                        <a href="javascript:;" class="collapse" data-original-title="" title=""></a>
                        <a href="javascript:;" class="fullscreen" data-original-title="" title=""></a>
                        <a href="javascript:;" class="remove" data-original-title="" title=""></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <div id='barChart'></div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock%}

{% block page_scripts %}

<script>
year = '{{year}}'
var colors = ["#E7505A","#3598DC","#36D7B7","#F7CA18","#BF55EC","#E87E04","#BFCAD1","#9C27B0","#795548"]
var production = {{ production | js }};
var production_data = []
for (i=0; i < production.length; i++){
    p = {
        'text':production[i]['name'],
        'values':[production[i]['sum']],
        'backgroundColor':colors[i]
    }
    production_data.push(p)
}

var production_plan_data=[]
var production_plan = {{production_plan | js}}
var labels =[]
for (var pkey in production_plan){
	name = pkey

	labels.push(name)
}

var type = {
	"san_xuat":"Sản xuất thực tế",
	"mua_sam":"Mua sắm thực tế",
	"kinh_doanh":"Kinh doanh thực tế"};

var count =0;

bar_values =[]
for (var pkey in production_plan){
    	detail = production_plan[pkey]
    	bar_values.push(detail['san_xuat']['ke_hoach'])
}
production_plan_data.push({'values':bar_values,'text':'Kế hoạch sản xuất','background-color':colors[count]})
count ++
for (var key in type) {
    values=[]
    for (var pkey in production_plan){
    	detail = production_plan[pkey]
    	values.push(detail[key]['thuc_te'])
    }
    console.log(values)
    production_plan_data.push({'values':values,'text':type[key],'background-color':colors[count]})
    count ++
}

var action = {
    contextMenu: {
      customItems: [
        {
          text: 'Show Alert',
          function: 'zingAlert()',
          id: 'showAlert'
        }
      ]
    },
    behaviors: [
      {
        id: 'showAlert',
        enabled: 'all'
      }
    ]
  }

var circleConfig = {
backgroundColor:'#FFFFFF',
 	type: "ring",
 	<!--title: {-->
 	  <!--text: "Kế hoạch sản xuất",-->
 	  <!--fontSize: 22,-->
 	  <!--// border: "1px solid black",-->
 	  <!--padding: "15",-->
 	  <!--fontColor : "#7E7E7E",-->
 	<!--},-->
 	plot: {
 	  size:'50%',
 	  slice:'60%',
 	  borderWidth:0,
 	  backgroundColor:'#FBFCFE',
 	  animation:{
 	    effect:2,
 	    sequence:3
 	  },
 	  valueBox: [
 	    {
 	      type: 'all',
 	      text: '%t',
 	      placement: 'out'
 	    },
 	    {
 	      type: 'all',
 	      text: '%npv%',
 	      placement: 'in'
 	    }
 	  ]
 	},
  tooltip:{
 	    fontSize:16,
 	    anchor:'c',
 	    x:'50%',
 	    y:'10%',
 	    sticky:true,
 	    backgroundColor:'none',
 	    borderWidth:0,
 	    thousandsSeparator:',',
 	    text:'<span style="color:%color">%t</span><br><span style="color:%color">%v</span><br><span style="color:%color">%npv%</span>',
      mediaRules:[
        {
            maxWidth:500,
       	    y:'47%',
        }
      ]
  },
 	plotarea: {
 	  backgroundColor: 'transparent',
 	  borderWidth: 0,
 	  borderRadius: "0 0 0 10",
      "margin-bottom": "50px"
 	},
 	"legend": {
                "layout": "2x3",
                "y": "0%",
                "x": "13%",
                 "item":{
                    "font-color":"grey",
                 },
                "overflow": "page",
                "alpha": 0.05,
                "shadow": false,
                "marker": {
                    "type": "circle",
                    "border-color": "none",
                    "size": "8px"
                },
                "border-width": 0,
                "maxItems": 5,
                "toggle-action": "remove",
                "pageOn": {
                    "backgroundColor": "#000",
                    "size": "10px",
                    "alpha": 0.65
                },
                "pageOff": {
                    "backgroundColor": "#7E7E7E",
                    "size": "10px",
                    "alpha": 0.65
                },
                "pageStatus": {
                    "color": "black"
                }
            },
 	scaleR:{
 	  refAngle:270
 	},
	series : production_data
};

zingchart.render({
	id : 'circleChart',
  data: {
    gui:action,
    graphset: [circleConfig]
  },
	height: '499',
	width: '99%'
});


zingchart.THEME="classic";
var barConfig = {
	gui: action,
    "graphset": [
        {
            "type": "bar",
            "background-color": "#FFFFFF",
            <!--"title": {-->
                <!--"text": "Kế hoạch và thực tế",-->
                <!--"font-color": "#7E7E7E",-->
                <!--"backgroundColor": "none",-->
                <!--"font-size": "22px",-->
                <!--"alpha": 1,-->
                <!--"y": "15px",-->
                <!--"x": "15px"-->
            <!--},-->
            "tooltip": {
                "text": "%v"
            },
            "value-box": {
      			"text": "%v",
    		},
            "plotarea": {
                "margin": "80 60 100 60",
                "y": "50px"
            },
            "legend": {
                "layout": "x4",
                "y": "0%",
                "x": "10%",
                "overflow": "page",
                "alpha": 0.05,
                "shadow": false,
                "marker": {
                    "type": "circle",
                    "border-color": "none",
                    "size": "8px"
                },
                "item":{
                    "font-color":"grey",
                 },
                "border-width": 0,
                "maxItems": 4,
                "toggle-action": "remove",
                "pageOn": {
                    "backgroundColor": "#000",
                    "size": "10px",
                    "alpha": 0.65
                },
                "pageOff": {
                    "backgroundColor": "#7E7E7E",
                    "size": "10px",
                    "alpha": 0.65
                },
                "pageStatus": {
                    "color": "black"
                }
            },
            "plot": {
                "animation": {
                    "effect": "ANIMATION_SLIDE_BOTTOM"
                }
            },
            "scale-x": {
                "line-color": "#7E7E7E",
                "labels":labels,
                "item": {
                    "font-color": "#7e7e7e"
                },
                "guide": {
                    "visible": false
                }
            },
            "scale-y": {
                "line-color": "#7E7E7E",
                "item": {
                    "font-color": "#7e7e7e"
                },

                "guide": {
                    "visible": true
                },
                "label": {
                  "text": "",
                  "font-family": "arial",
                  "font-angle":0,
                  "bold": true,
                  "font-size": "14px",
                  "font-color": "#7E7E7E",
                  "offset-y":"-190px",
                  "offset-x":"20px"
            },
            },
            "series": production_plan_data
        }
    ]
};

zingchart.render({
	id : 'barChart',

  	gui:action,
	data : barConfig,
	height: 500,
	width: 725
});

zingchart.node_click = function(data){
			id = data["id"]
            nodeid = data["nodeindex"]
            plotid = data["plotindex"]
            ip = document.location.hostname
            if (id == 'circleChart'){
            	productname = production[plotid]['name']
            	window.location = "http://" + ip + ":8000/erp/detail/" + productname;
            } else if (id == 'barChart'){
            	var keys = Object.keys( production_plan );
            	productname = keys[nodeid]
            	console.log((document.location.hostname))

            	window.location = "http://" + ip + ":8000/erp/detail/" + productname;
            }
       }

</script>
{% endblock%}